GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8081/products/1/ HTTP/1.1

###

PUT http://localhost:8081/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMDA4Mjg5LCJpYXQiOjE3NjAwMDc5ODksImp0aSI6IjdjNjJhNzEzZTVhYjQ4Zjg4ZjM4MDY3NmVjMDc3NWYzIiwidXNlcl9pZCI6IjIifQ.KTZaN8gn0il56SPxwgsrKbNyrixGMW7zxwUtKRx7Zjs

{
    "name":"keyboard",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new phone"
}

###
DELETE http://localhost:8000/products/1/ HTTP/1.1




###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "TV",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###
POST http://localhost:8080/api/token/ HTTP/1.1
Content-Type: application/json

{
    "email":"shekemal@gmail.com",
    "password":"password123"
}

###

POST http://localhost:8081/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDA5Mjg3MSwiaWF0IjoxNzYwMDA2NDcxLCJqdGkiOiIyNzY1MmFiMTY3NWI0NTExOTYxNmExOWE2N2U1NjI4YyIsInVzZXJfaWQiOiIyIn0.Q9Sa7CXdU7uAGKwMzJY6g8JelDDccrUGdvswnDwemo4"
}


###

GET http://localhost:8080/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNTU3NDk0LCJpYXQiOjE3NjA1NTcxOTQsImp0aSI6IjdkNTVjNDQ4ZmIxNzRkMzFhNzU5NTJjZDAwNDI5ZTI0IiwidXNlcl9pZCI6IjEifQ.1KlZaFTOu9BbDboYRIsgPT6xaO4UMFbmEWblafk4blA

###
POST  http://localhost:8080/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwOTMzMTc4LCJpYXQiOjE3NjA5MzI4NzgsImp0aSI6IjQ5N2UxMGVhNWRhODQwMjU4NWUxYTkxMGM5ZDk3NTVmIiwidXNlcl9pZCI6IjEifQ.C6SASFTt9x5E7NclluR9alkkz7XHuYlWIWAgE6jy0_c


{
    "status" : "Pending",
    
    "items":[
        {
            "product":2,
            "quantity":1000

        }, 
        {
         "product":3,
        "quantity":500
        }
    ]
}
###

PUT http://localhost:8080/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwOTMxODMxLCJpYXQiOjE3NjA5MzE1MzEsImp0aSI6IjY2OTlmZDUxMjhiZDQzYzRhOTRmNjg4NzZjZGU2OGRmIiwidXNlcl9pZCI6IjEifQ.5yd-FxlsStcKNKx7oHGMD-M-q535dIgOSxxDZYGmCAY

{
    "status" : "Confirmed",
 
    "items":[
        {
            "product":20,
            "quantity":20

        }, 
        {
         "product":20,
        "quantity":20
        }
    ]
}

### 

GET http://localhost:8080/orders/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNTU4MjU5LCJpYXQiOjE3NjA1NTc5NTksImp0aSI6ImVhOWRmMmIwN2IwNDRjYTM5ZTAyMmEzZmIzMzJhMzdmIiwidXNlcl9pZCI6IjMifQ.2W_-8LAygyInUohDKHirbfZIDccGqQtH3QBlWUQdcms
