#!/bin/bash

DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-"abasimelahmed@gmail.com"}
DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-"password"}

cd /app/

/opt/venv/bin/python manage.py migrate --noinput
# Create superuser only if it doesn't exist
/opt/venv/bin/python3 manage.py shell << END
from django.contrib.auth import get_user_model
User = get_user_model()
if not User.objects.filter(email="$DJANGO_SUPERUSER_EMAIL").exists():
    User.objects.create_superuser("$DJANGO_SUPERUSER_EMAIL", password="$DJANGO_SUPERUSER_PASSWORD")
END || true
